export const LOCATIONS = [
    "Buttrick Hall",
    "Kirkland Hall",
    "Wilson Hall",
    "Garland Hall",
    "Stevenson Center",
    "Featheringill Hall",
    "Blair School of Music",
    "Owen Graduate School of Management",
    "Law School",
    "Medical Center",
    "Commons Center",
    "Branscomb Quadrangle",
    "Carmichael Towers",
    "Highland Quadrangle",
    "Warren College",
    "Moore College",
    "Zeppos College",
    "Student Life Center",
    "Recreation and Wellness Center",
    "Rand Dining Center",
    "Sarratt Student Center",
    "Student Union",
    "Central Library",
    "Biomedical Library",
    "Divinity Library",
    "Music Library",
    "Vanderbilt Stadium",
    "Memorial Gymnasium",
  ];