export const LOCATIONS = [
   "Commons Center",
   "Moore College",
   "Warren College",
   "Rothchild College",
   "Zeppos College",
   "Carmichael College",
   "Highland Quadrangle",
   "Rand Dining Center",
   "Buttrick Hall",
   "Kirkland Hall",
   "Wilson Hall",
   "Garland Hall",
   "Featheringill Hall",
   "Blair School of Music",
   "Owen Graduate School of Management",
   "Law School",
   "Medical Center",
   "Student Life Center",
   "Recreation and Wellness Center",
   "Stevenson Library",
   "Central Library",
   "Biomedical Library",
   "Divinity Library",
   "Vanderbilt Stadium",
   "Memorial Gymnasium",
];
